# Generated by Django 2.2.8 on 2019-12-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
