# Generated by Django 2.2.8 on 2020-01-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20200105_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
