# Generated by Django 2.2.8 on 2019-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191226_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
