# Generated by Django 2.2.8 on 2020-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='recent',
            field=models.ManyToManyField(related_name='recent', to='actions.Diary'),
        ),
    ]
